#!/usr/bin/env bash
# MIT © Sindre Sorhus - sindresorhus.com

# git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.git/hooks/`.

changed_folder="$(git diff --name-only --diff-filter=ADMR ORIG_HEAD HEAD)"

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_folder_run() {
	echo "$changed_folder" | grep --quiet "$1" && eval "$2"
}

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# change chmod storage and bootstrap/cache folder
sudo chmod -R 777 storage bootstrap/cache

# run command generate api document
php artisan l5-swagger:generate

# `npm install` and `npm prune` if the `package.json` file gets changed
# to update all the nodejs (grunt) dependencies deleting the unused packages (not listed into the `package.json` file)
check_run package.json "npm install && npm prune"

# `composer install` if the `composer.json` file gets changed
# to update all the php dependencies
check_run composer.json "composer install"

# check if folder resources/js or resources/css or resources/images gets changed, run `npm run production`
check_folder_run "resources/js\|resources/css\|resources/images" "npm run production"

# check if folder database/migrations gets changed, run php artisan migrate
check_folder_run "database/migrations" "php artisan migrate"

# clear opcache && cache
php artisan opcache:clear
php artisan cache:clear
composer dump-autoload
