#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Lint..."
for FILE in $SFILES
do
    php -l -d display_errors=0 $PROJECT/$FILE
    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        exit 1
    fi

    RESULT=$(grep -i "dd(" "$FILE")
	if [ ! -z $RESULT ]
	then
		echo "Warning, the commit contains a call to dd() in $PROJECT/$FILE"
		exit 1
	fi

	RESULT=$(grep -i "die" "$FILE")
	if [ ! -z $RESULT ]
	then
		echo "Warning, the commit contains a call to die in $PROJECT/$FILE"
		exit 1
	fi

	RESULT=$(grep -i "var_dump(" "$FILE")
	if [ ! -z $RESULT ]
	then
		echo "Warning, the commit contains a call to var_dump() in $PROJECT/$FILE"
		exit 1
	fi

    FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
    echo "Running Code Sniffer. Code standard PSR2."
    ./vendor/bin/phpcs --standard=PSR2 --ignore=*/node_modules/*,*/public/*,*/database/*,*/tests/* --tab-width=4 --encoding=utf-8 -s -n -p $FILES
    if [ $? != 0 ]
    then
        echo "Fix the error before commit!"
        echo "Run"
        echo "  ./vendor/bin/phpcbf --standard=PSR2 --ignore=*/node_modules/*,*/public/*,*/database/*,*/tests/* --tab-width=4 --encoding=utf-8 -s -n -p $FILES"
        echo "for automatic fix or fix it manually."
        exit 1
    fi
fi

exit $?
